project:
  type: default
  execute-dir: project # the working directory for computations
  output-dir: _outputs
  
author: 
  - name: Maël Delem
    orcid: 0009-0005-8518-1991
    email: mael.delem@univ-lyon2.fr
    url: https://scholar.google.com/citations?user=Oiv7mtQAAAAJ&hl=fr&oi=ao

# ─── Common options ───
date-format: "D/MM/YYYY"
date-modified: last-modified

bibliography:
  - "bibliography/references.bib" 
  - "bibliography/packages.bib"
csl: "bibliography/apa.csl"

execute:
  freeze: false
  warning: false
  error: false
  message: false

toc: true
number-sections: true
crossref:
  chapters: true

# ─── Format-specific options ───
format:

  html:
    embed-resources: true  # self-contained HTML rendering
    
    # styling
    theme: 
      dark: darkly
      light: flatly
    css: "_extensions/html/custom.css"
    # importing Montserrat font
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    mainfont: Montserrat
    fontsize: "medium"
    
    # interactive features
    lightbox: true          # clickable figures
    code-fold: true         # code folding for clarity
    code-annotations: hover # show code annotations on hover
    
    # HTML-specific TOC options
    toc-location: right
    toc-depth: 2
    toc-expand: 1
    number-depth: 2

